### ISSUE TITLE
Getting 502 error when trying to get music url

### ISSUE THREAD

**Issue by upendra-web** [Binaryify/NeteaseCloudMusicApi#579]
Made a git clone and started the api at 8008.

I made a request to 'http://localhost:8008/song/url?id=33894312'

I am getting this error:
```json
{  
   "code":502,
   "msg":"Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: music.163.com. is not in the cert's altnames: DNS:fjm.name, DNS:www.fjm.name\n    at Object.checkServerIdentity (tls.js:239:17)\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1068:27)\n    at TLSSocket.emit (events.js:198:13)\n    at TLSSocket._finishInit (_tls_wrap.js:636:8)"
}
```

Can u help me with this issue?

**Comment by nondanee** [comment]
I'm pretty sure you are using the project [fengjueming/unblock-NetEaseMusic](https://github.com/fengjueming/unblock-NetEaseMusic)

Related issue 👉 https://github.com/fengjueming/unblock-NetEaseMusic/issues/29

Please remove the record `158.199.142.239 music.163.com` from your hosts file

**Comment by upendra-web** [comment]
Okay, can u tell me an alternative for '158.199.142.239 music.163.com'?

**Comment by nondanee** [comment]
Sorry, I can't

In general, this kind of reverse proxies can't provide https service because
no one owns the **certificate's private key** except netease itself

If you cannot drop that hosts record

Another way
https://github.com/Binaryify/NeteaseCloudMusicApi/blob/98bb2928728d56c64dafb1c4b3a9ed33c7e7728d/module/song_url.js#L13
Change the url protocol from `https` to `http` for every route you want to use
